### ISSUE TITLE
chore(ci): enforce type hints with MyPy

### ISSUE THREAD

**Issue by jeertmans** [jeertmans/manim-slides#37]
# What

In par with #34, I'd like to have some checks to assert that all functions, methods, and constants have type hints.

# How to

This PR requires adding a pre-commit hook that using mypy. After the `flake8` hook:

https://github.com/jeertmans/manim-slides/blob/14a266b139fa87b77617e93e52920412fe8059ab/.pre-commit-config.yaml#L22-L30

you need to add:

```yaml
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
```

and use customized arguments to make sure it only checks for type hints.

# Useful links

* [Using mypy's pre-commit hook](https://github.com/pre-commit/mirrors-mypy)
* [How to force type hint with mypy](https://stackoverflow.com/questions/55944201/python-type-hinting-how-do-i-enforce-that-project-wide)
